## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboots?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

## mybatis配置
mybatis:
  typeAliasesPackage: com.dengqi7.domain
  mapperLocations: classpath:mapper/*.xml

##通用mapper配置
mapper:
  mappers: com.dengqi7.mapper.BaseMapper,tk.mybatis.mapper.common.MySqlMapper
  notEmpty: true


